# Generated by Django 4.1.6 on 2023-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
